services:
  device_agent:
    image: spaneng/doover_device_agent:apps
    network_mode: host
    attach: false

  sample_simulator:
    build: ./sample
    network_mode: host
    restart: unless-stopped
    depends_on:
      device_agent:
        condition: service_healthy
    environment:
      - APP_KEY=sim_app_key

  sample_foxglove:
    build: ../
    network_mode: host
    restart: unless-stopped
    # depends_on:
    #   - device_agent
      # - sample_simulator
    depends_on:
      device_agent:
        condition: service_healthy
    environment:
      - APP_KEY=test_app_key
      - HEALTHCHECK_PORT=49201
      # - CONFIG_FP=/app_config.json
    # volumes:
    #   - ./app_config.json:/app_config.json
    ports:
      - "8765:8765"
